### ISSUE TITLE
Optimized WorldWind graphics are not set to CLAMP_TO_GROUND

### ISSUE THREAD

**Issue by jaybarra** [missioncommand/emp3-web#281] opened 2017-04-24 17:13 UTC
They default to ABSOLUTE and not CLAMP_TO_GROUND

**Comment by alberto-acevedo** [comment] 2017-05-12 20:55
The placemark (dot) is already set to clampToGround. The problem is that there is no way to set its vertical origin.  I opened an issue in WW sdk:

https://github.com/NASAWorldWind/WebWorldWind/issues/120

**Comment by alberto-acevedo** [comment] 2017-05-15 13:17
Snapshot  showing the issue. The dot is floating on the air when the altitude mode is clampToGround.

![image](https://cloud.githubusercontent.com/assets/2699867/26059298/480624e4-394f-11e7-936f-d0efc08a2f1e.png)

**Comment by alberto-acevedo** [comment] 2017-05-15 18:01
The EMP map was reusing the imageOffset of the mil standard icon when switching to a dot placemark. Setting the dot image offset to .5, .5 fixed the issue. The issue was not in  WebWorldWind.

**Comment by alberto-acevedo** [comment] 2017-05-15 18:08
Test case:

Use the branch 2.6.0

Use WW.

Plot a mil std single point  (any). Zoom out until the icon switches to a dot. Tilt the map. The test is a success if the dot is on the terrain (not floating in mid air).

**Comment by mubinakhan** [comment] 2017-05-15 19:06
Reinetgrate

**Comment by alberto-acevedo** [comment] 2017-05-16 12:28
Merged into the release 2.6.0 branch. closing this issue.

**Closed** 2017-05-16 12:28 UTC
Labels: [Bug] Minor, [Engine] WorldWind, [Status] Blocked, [Status] Ready
