### ISSUE TITLE
Implement Feature.buffer property for primitives in Cesium

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#29] opened 2017-02-03 15:38 UTC

**Comment by alberto-acevedo** [comment] 2017-02-15 14:54
Snapshot of rectangle with corresponding modifiers with buffer (first value of AM array)

![rectangle buffer and modifiers failed to add buffer](https://cloud.githubusercontent.com/assets/2699867/22979442/6596d1d8-f364-11e6-85b9-47433a1623cc.png)

**Comment by alberto-acevedo** [comment] 2017-02-15 14:56
The rectangle should render as a square with a buffer but it is rendering as a rectangle with no buffer. Third value of AM array is ignored.

**Comment by alberto-acevedo** [comment] 2017-02-15 14:57
Mike, take a look to the snapshot. What is wrong with the modifiers?

**Comment by mdeutch3** [comment] 2017-02-15 15:17
BBS_RECTANGLE takes two points to define opposite corners of the rectangle and uses AM[0] in meters to define the buffer to define the fill area.

**Comment by mdeutch3** [comment] 2017-02-15 16:43
Not currently. I will look into adding a buffer. PBS_RECTANGLE takes AM[0] and AM[1] for the width and height and AN[0] for the azimuth. I’ll look into adding AM[2] for the buffer in meters. It should not conflict with clients that use PBS_RECTANGLE.

**Comment by alberto-acevedo** [comment] 2017-02-16 15:19
Ok. Thanks.

**Comment by mdeutch3** [comment] 2017-02-17 18:55
The metric buffer has been implemented for all the parameterized symbols, including rectangle, square, ellipse, and circle. For all symbols please use AM[2] for the buffer size. The code has been checked into mil-sym-js repository.

**Comment by alberto-acevedo** [comment] 2017-02-17 19:43
Ok. I will try it out. Thanks!

**Comment by alberto-acevedo** [comment] 2017-02-17 20:56
I tried with a parameterized rectangle. When I set the buffer I see that the size of the rectangle increasing but the rectangle is completely shown  solid with the same color applied to the rectangle and buffer. I was expecting the buffer with the applied fill color and the rest of the rectangle with no fill color. See attached snapshot:
![image](https://cloud.githubusercontent.com/assets/2699867/23082960/976efa5c-f529-11e6-9ba7-117edd11b444.png)

**Comment by mdeutch3** [comment] 2017-02-17 21:03
You would need less than FF for the alpha value to see the outline. Try 55FF0000 for the fill color.

**Comment by alberto-acevedo** [comment] 2017-02-17 21:12
Yes, that worked!
![image](https://cloud.githubusercontent.com/assets/2699867/23083479/ddb62b50-f52b-11e6-9226-93a09487839a.png)

**Comment by alberto-acevedo** [comment] 2017-02-21 14:14
Mike,

There  is a function in Cesium sdk that calculates the points for ellipses. The function does very well for large graphics. The function and how to use it:

var circleComputed = Cesium.EllipseGeometryLibrary.computeEllipsePositions({
                semiMajorAxis: 500000,
                semiMinorAxis: 500000,
                rotation: 0,
                center: viewer.scene.globe.ellipsoid.cartographicToCartesian(Cesium.Cartographic.fromDegrees(45.0, 45.0)),
                granularity : 0.02
        }, false,true);

Can this function help the SEC renderer to improve the 2D rendering of large circular shapes like isolate?

Thanks

**Comment by mdeutch3** [comment] 2017-02-21 16:32
I will look into this when I get a chance. I don't know what the Cesium dependencies area. Please note that a change was checked in for the PBS shapes so that the outline will appear on top regardless of fill opacity. However, if the fill and line opacity are the same then the color must be different for the outline to appear.

**Comment by mdeutch3** [comment] 2017-02-21 16:34
'area' should read 'are' in the 2nd sentence above.

**Comment by alberto-acevedo** [comment] 2017-02-21 18:05
Ok, thanks.

**Comment by mdeutch3** [comment] 2017-02-21 23:39
We don't have a problem rendering circles. For example FSA Circular, symbol code G*FPACSC--****X, displays Ok with a radius of 200000. The problem is that isolate and the other tasks are pixels based circles. but we are using a 2D converter on a 3D surface so it does not work well. When I get a chance I need to see if I can process these symbols similar to how we process FSA Circular instead of using pixels.

**Comment by alberto-acevedo** [comment] 2017-02-22 16:47
I tested the buffer with circles wit a radius of 2000000 and it looks deformed. I compared it with the FSA circle and the FSA looks perfect. So I assume the circle with buffer  is based on pixels. The FSA circle  and the circle with the buffer have both a category of circle parametirized,  I was expecting the circle with buffer not to be based in pixels like FSA See snapshot:

Thanks.


![image](https://cloud.githubusercontent.com/assets/2699867/23221488/3d491846-f8f3-11e6-94ae-222db9b7e6c0.png)

**Comment by mdeutch3** [comment] 2017-02-22 16:58
I will look at processing PBS circle and ellipse and the circular tasks like how we handle FSA Circular.

**Comment by alberto-acevedo** [comment] 2017-02-22 20:53
Test case:

Plot circle, ellipse, square, rectangle.
For each shape set the buffer, and a fill color and outline color. The Fill color  and outline color have be different colors for the boundary of buffer  to be visible.

**Comment by jamesbeecroft** [comment] 2017-02-23 19:58
Reintegrate

**Comment by alberto-acevedo** [comment] 2017-02-24 21:36
Merged into the dev branch. Closing this issue.

**Closed** 2017-02-28 15:31 UTC
Labels: [Engine] Cesium, [Type] New Feature
