### ISSUE TITLE
Map.setFreehandStyle initialStyle parameter causes freehand line to draw with wrong colors

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#28] opened 2017-02-03 15:35 UTC
Set the line color for Map.setFreehandStyle and then try drawing Freehand lines. Set it to be red and it drew green. Set it to green and it drew blue. All messed up.

**Comment by erikamarie** [comment] 2017-03-13 14:02
Could not reproduce the issue as described. Found that the tester failed only if user entered less than 8 character hex value. Changed tester to accept 6 and append transparency. All colors tested worked in Cesium and Leaflet. Worldwind does not currently support stroke color changes. Colors test: d400ee (fuschia) 03f4e3 (light blue) and f5c617 (yellow) with and without transparency of "ff"

**Comment by jamesbeecroft** [comment] 2017-03-13 16:14
Reintegrate. Could not duplicate color selection issue resulting in incorrect color of the line. The Stroke Style tool in the map.drawfreehand to set the stroke color and stroke width values does not work (Validation Tool).

**Comment by michael-spinelli** [comment] 2017-06-20 18:12
Alberto, verify this.  Sounds like it was done already from reading the comments.  Maybe forgot to close or forgot to merge.

**Comment by alberto-acevedo** [comment] 2017-06-20 19:07
I just tested in the dev branch and there is no issue.

-----Original Message-----

**Comment by alberto-acevedo** [comment] 2017-06-20 19:13
Not able to replicate the issue. Closing this issue

**Closed by alberto-acevedo** 2017-06-20 19:13 UTC
Labels: [Bug] Major, [Component] API, [Component] Core
