### ISSUE TITLE
Map.onSuccess not working properly

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#326] opened 2017-06-09 20:08 UTC
Map.onSuccess callback is called, but then the map goes back into an initializing state.  While it is in this initializing state, the Map methods do not work.  Then the map swaps back to ready after the engine correctly reports the readiness.  During that period of swapping between ready, initializing, and ready again, map calls are failing as the map is indicating it is not ready, even though the onSuccess is called.

**Comment by michael-spinelli** [comment] 2017-06-12 19:46
is this a leaflet or core issue?

**Comment by sjpinizzotto** [comment] 2017-06-12 19:52
this is core issue.

**Comment by alberto-acevedo** [comment] 2017-06-29 20:18
I tested the development branch and the  emp.map.status  (line 1434) sequence I was getting when starting a new map is as follows:

idle
init
ready

When doing a map swap the status sequence is as follows:

ready
mapswappinginprogress
ready

I was not able to see the bad sequence:

ready
initializing
ready

Do you have a script that could replicate the issue? Under what circumstances were you getting the bad sequence?

**Comment by alberto-acevedo** [comment] 2017-07-12 20:01
I was able to see the issue.  It is a timing issue. The API and core have their own property for map status. When the AP.Map is created the status is immediately set to 'ready' (assuming by design). For the case of the core the setting of the status from 'idle' to 'initialization' is happening in a non synchronized mode inside a timeout located in the emp.instanceManager/buildInstance function. The api map finish its initialization without waiting for the engine to be ready (assuming it is by design)  and calls the map.onSuccess. While overlays and features are added inside the map.onSuccess, requests are sent to core map  transaction queue until the engine sends the map status  of 'ready'.  Nothing is rendered on the map until the engine sends the ready status. while this process of the client sending overlays and features happens, there is no initialization status synchronization with the core map and the status could change from ''ready' or 'idle'  to 'initialization' in the middle of the of the API processing requests. When the status is changed to 'initialization', all requests are queued again giving the impression that the map is failing to render the overlays and respective features. I propose setting the core map status to 'initialization' outside of the timeout to keep the process and status  in synch.  Cesium is also sending the ready status in a non synchronize mode to complicate things. The fix will prevent the case of a  'ready' status changing to 'initialization' status.

 Below is the sample script that creates a Cesium map, creates an overlay, several features are added to the overlay, and a loop is execute to hide /unhide features on the map. All the rendering is called from within the map.onSuccess. 

Use branch 326.

The test is successful if features are rendered on the map and then they keep hiding/unhiding continuously. 


Create a testMapOnSuccess.html page inside the tomcat server webApps/emp3-map folder. Paste the following script inside the html file:

<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="EMP3 Map Widget">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>EMP3 Map Widget</title>
    
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="images/touch/chrome-touch-icon-192x192.png">
    
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="EMP3 Map Widget">
    <link rel="apple-touch-icon-precomposed" href="apple-touch-icon-precomposed.png">
    
    <meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
    <meta name="msapplication-TileColor" content="#3372DF">
    <link href="vendor/mil-sym/renderer.css" rel="stylesheet" type="text/css"/>

    <style>
        .leaflet-control-zoom {
            display: none;
        }

        .cesium-widget-cesiumNavigationContainer {
            display: none;
        }
    </style>

</head>

<body>
<div style="position: absolute; top: 0; left: 0; right: 0; bottom: 0;" id="empmap"></div>
<script src='vendor/jquery-1.11.2.min.js' type="text/javascript"></script>
<script src='vendor/mil-sym/savm-bc.js' type="text/javascript"></script>
<script src='emp3/emp3.min.js' type="text/javascript"></script>

<script>
    var config = { // The map configuration parameters for this test.
        environment: "browser",
        debug: false,
        scriptPath: "js",
        distPath: "",
        urlProxy: "urlproxy.jsp",
        engineBasePath: "emp3/",
        startMapEngineId: 2,
        wmsServerUrls: [],
        mapEngines: [{
            "id": 2,
            "name": "Cesium",
            "mapEngineId": 'cesiumMapEngine',
            "url": "emp3-cesium/manifest.js",
            "properties": {
                "defaultImageryUrl": "http://localhost:8080/geoserver/wms",
                "data": "[{'type' : 'osm','name' : 'Open Street Map','url' : '//a.tile.openstreetmap.org','disableProxy' : 'true','disable' : 'false','options' : '' },\n\
                                     {'type' : 'bing','name' : 'Bing Aerial','url' : 'https://dev.virtualearth.net','disableProxy' : 'true','disable' : 'false','options' : 'Cesium.BingMapsStyle.AERIAL' },\n\
                                     {'type' : 'arcgis93rest','name' : 'ESRI World Map','url' : 'https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer','disableProxy' : 'true','disable' : 'false','options' : '0' },\n\
                                     {'type' : 'arcgis93rest','name' : 'ESRI Street Map','url' : 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer','disableProxy' : 'true','disable' : 'false','options' : '0' }\n\
                                     ]"
            }
        }, {
            "id": 1,
            "name": "Leaflet",
            "mapEngineId": 'leafletMapEngine',
            "url": "emp3-leaflet/manifest.js",
            "properties": {
                "data": "{'Use_Proxy_For_Map_Request':false,'Use_Proxy_For_Default_Map_Request':false,'Minimum_Zoom_Level':1,'Maximum_Zoom_Level':11,'Default_Tile_Map_Server_URL':'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'}"
            }
        }]
    };

</script>
<script type="text/javascript">
var map1;
    $(document).ready(function () {
         map1 = new emp3.api.Map({
            engine: {
                "mapEngineId": 'cesiumMapEngine',
                "engineBasePath": "./emp3/emp3-cesium/"
            },
            container: "empmap",
            config: config,
            onSuccess: function () {
                console.log("Map creation success.");
                runExample();
            },
            onError: function (args) {
                console.log("Map creation failed.");
            }
        });
    });

    function runExample(){

	  try{

	  var polygon = new emp3.api.Polygon({
	    name: "Polygon",
	    positions: [{
	      latitude: 40,
	      longitude: 39
	    }, {
	      latitude: 40.5,
	      longitude: 39.5
	    }, {
	      latitude: 40,
	      longitude: 40
	    }]
	  });

	  var armor = new emp3.api.MilStdSymbol({
	    name: "Armor",
	    positions: [{
	      latitude: 40,
	      longitude: 40.5
	    }],
	    symbolCode: "SFGPUCA----K---"
	  });

	  var boundary = new emp3.api.MilStdSymbol({
	    name: "Boundary",
	    positions: [{
	      latitude: 40,
	      longitude: 42
	    }, {
	      latitude: 41,
	      longitude: 43
	    }, {
	      latitude: 40,
	      longitude: 44
	    }],
	    symbolCode: "GFGPGLB----I--X", // Division Boundary line
	    modifiers: {
	      uniqueDesignation1: "1BDE",
	      uniqueDesignation2: "2BDE"
	    }
	  });

	  // create an Overlay to contain the features.
	  var overlay1 = new emp3.api.Overlay({
	    name: "overlay1",
	    geoId: "w834mne-sdg5467-sdf-we45"
	  });

	  var visibility = emp3.api.enums.VisibilityActionEnum.TOGGLE_ON;

	  var changeOverlayVisibility = function() {
	    // turn off/on the overlay every 2 seconds.
	    setInterval(function() {
	      map1.setVisibility({
	        target: overlay1,
	        action: visibility
	      });

	      if (visibility === emp3.api.enums.VisibilityActionEnum.TOGGLE_ON) {
	        visibility = emp3.api.enums.VisibilityActionEnum.TOGGLE_OFF;
	      } else {
	        visibility = emp3.api.enums.VisibilityActionEnum.TOGGLE_ON;
	      }
	    }, 2000);
	  };

	  var addFeatures = function() {

	    // Zoom to the newly added feature
	    // Add the MilStdSymbol to the overlay
	    overlay1.addFeatures({
	      features: [polygon, armor, boundary], // adds multiple features at once.  Faster than adding one at a time.
	      onSuccess: function() {
	        map1.zoomTo({
	          overlay: overlay1
	        });

	        changeOverlayVisibility();
	      }
	    });
	  };

	  // Add the overlay to the map.
	  map1.addOverlay({
	    overlay: overlay1,
	    onSuccess: function() {
	      addFeatures();
	    },
	    onError: function(error) {
	      alert(JSON.stringify(error));
	    }
	  });

	  } catch(e) {

	     console.log ("Error: " + (e.lineNumber ? (" line " + e.lineNumber) + ", " : "") + e.message); }

  }


</script>

</body>

</html>

**Comment by alberto-acevedo** [comment] 2017-07-12 20:03
Mike, please review the fix in the core.

**Comment by michael-spinelli** [comment] 2017-07-13 14:27
Looks good

**Comment by alberto-acevedo** [comment] 2017-07-13 18:03
Merged into the dev branch. Closing this issue.

**Closed** 2017-07-13 18:03 UTC
Labels: [Status] Ready
