### ISSUE TITLE
Icon Size not changing in Leaflet

### ISSUE THREAD

**Issue by jamesbeecroft** [missioncommand/emp3-web#198] opened 2017-03-29 17:31 UTC
Mil-Std unit and graphics icons are not changing size in Leaflet, when the user applies the change.

**Comment by alberto-acevedo** [comment] 2017-07-05 12:56
Duplicate of issue #299 that was fixed in sprint 2.8. Closing this issue.

**Closed** 2017-07-05 12:57 UTC
Labels: [Bug] Major, [Component] Validation, [Engine] Leaflet
