### ISSUE TITLE
Map.drawFeature in Cesium for Points show different graphic then after it's drawn

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#336] opened 2017-06-21 21:56 UTC
Was using the draw capability in Cesium when I noticed the the Point that is added on the map prior to the drawComplete is issued is a different graphic then what shows up after the drawComplete.  The one shown on the drawComplete is the correct graphic that displays on all the other maps.   furthermore the graphic that is shown when I clicked is misaligned in the wrong spot of where I clicked.   After the drawComplete it appears to go to the right spot.

**Comment by alberto-acevedo** [comment] 2017-10-06 18:49
Not able to reproduce. Closing this issue.

**Closed** 2017-10-06 18:50 UTC
Labels: [Status] In Progress
