### ISSUE TITLE
Map.setSelectionStyle does not update features that are already selected on the map

### ISSUE THREAD

**Issue by sjpinizzotto** [missioncommand/emp3-web#43] opened 2017-02-03 19:01 UTC
It will only work for the next item that is selected.

**Comment by jamesbeecroft** [comment] 2017-02-09 20:58
Selection style updates are still not being applied to selected items on the map. Cesium is showing an error indicating the line color is null.

**Comment by alberto-acevedo** [comment] 2017-02-10 14:01
Not able to replicate issue that Jimmy was having. I think the issue was caused by the existance of 2 barnches with the same name but having bugFix and bugfix (upper case F). Steve removed the branch having teh upper case F. Try again.

**Comment by jamesbeecroft** [comment] 2017-02-10 19:20
reintegrate

**Comment by alberto-acevedo** [comment] 2017-02-10 19:39
Merged into the dev branch. closing this issue.

**Closed** 2017-02-14 13:50 UTC
Labels: [Bug] Major, [Engine] Cesium
